<?php

namespace Tests\Unit;


use Bright\Aliyun\Green\GreenService;
use Bright\Aliyun\Oss\FileContract;
use PHPUnit\Framework\TestCase;

class GreenTest extends TestCase
{

    /**
     * @var GreenService
     */
    public $mtsService;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /**
         * ALIYUN_MTS_REGION_ID=cn-shanghai
         * ALIYUN_MTS_ACCESS_ID=
         * ALIYUN_MTS_ACCESS_KEY=
         * ALIYUN_MTS_PIPELINE_ID=3500393f3f5b4a9c99ee078d550eed90
         */
        $mtsRegion = 'cn-shanghai';
        $accessKeyId = '';
        $accessKeySecret = '';
        $this->mtsService = new GreenService($accessKeyId, $accessKeySecret, $mtsRegion);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testSubmitSyncSnapshotJob()
    {


        $result = $this->mtsService->videoAsyncScan(["porn"], [
            [
                "dataId" => "videoId xxx",
                "url" => "",
                "interval" => 1,
                "maxFrames" => 200
            ]
        ], ["antispam"]);
        print_r($result->toJson());
        $this->assertEquals('Success', $result->State);
    }

    public function testVideoAsyncScanResults()
    {
        $input = new FileContract('oss-cn-shanghai', '',
            '');

        $result = $this->mtsService->videoAsyncScanResults(['']);
        print_r($result->toJson());
        $this->assertEquals('Success', $result->State);
    }
}
